"""
Django settings for task2 project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-yvt55m54gqpq!qm%2_ed1&^ahe&yn#-n6wnp)9mhm+g+zt*%q6'

DEBUG = True

ALLOWED_HOSTS = ['*']

STOCK_API_BASE_URL = 'http://20.244.56.144/evaluation-service'
API_CACHE_TTL = 60 
ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZXhwIjoxNzQ2Nzk3NDUyLCJpYXQiOjE3NDY3OTcxNTIsImlzcyI6IkFmZm9yZG1lZCIsImp0aSI6IjgzNDQwZGE4LTFmNjctNGZhNy05YjYyLWE3M2NhMTg0MjkxMSIsInN1YiI6ImFheXVzaGtlci4yMjI2Y3NlYWkxQGtpZXQuZWR1In0sImVtYWlsIjoiYWF5dXNoa2VyLjIyMjZjc2VhaTFAa2lldC5lZHUiLCJuYW1lIjoiYWF5dXNoa2VyIHNpbmdoIiwicm9sbE5vIjoiMjIwMDI5MTUyMDAwNiIsImFjY2Vzc0NvZGUiOiJTeFZlamEiLCJjbGllbnRJRCI6IjgzNDQwZGE4LTFmNjctNGZhNy05YjYyLWE3M2NhMTg0MjkxMSIsImNsaWVudFNlY3JldCI6InJDQ05GZkZ5WEREdktLc3IifQ.UWCyhIrAibZCa6F8AOkWqwEzX1NLAkYU-PM2xH1BNlI"



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stocks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'task2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'task2.wsgi.application'



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
